export const ACTION_TYPES = {
  SET_PROFILES: "SET_PROFILES",
  ADD_TASK: "ADD_TASK",
  REMOVE_TASK: "REMOVE_TASK",
  TOGGLE_TASK_COMPLETION: "TOGGLE_TASK_COMPLETION",
  SELECT_PROFILE: "SELECT_PROFILE",
} as const;
